import type { Metadata } from "next";
import {Inter, Poppins} from "next/font/google"
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  weight: ["100","200", "300", "400", "500", "600", "700", "800", "900"],
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ["100","200", "300", "400", "500", "600", "700", "800", "900"],
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${inter.className} ${poppins.className} antialiased font-poppins`}
      >
        <ThemeProvider attribute={"class"} defaultTheme='light' enableSystem disableTransitionOnChange>
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}